before_script:
  - echo '' > /home/gitlab-runner/.ssh/known_hosts
  - ssh-keyscan -t ed25519 3.213.159.140 > /home/gitlab-runner/.ssh/known_hosts
  - cat /home/gitlab-runner/.ssh/known_hosts

deploy_production:
  environment:
    name: precision
  script:
    - npm ci
    - cd precision-docs-deploy && npm ci && npx tsc && cd ..
    # npm run test, minus "js-test" because it does not work on Amazon Linux
    - npm-run-all lint dist docs-build docs-lint
    - npm run netlify
    - node precision-docs-deploy
    - rsync -amz --delete _site/ cloud-qa:/var/app/cloud/htdocs/bootstrap
  only:
    - precision